import os
import re
import shutil
import yt_dlp
from typing import Optional


def _find_ffmpeg_path() -> Optional[str]:
    """查找 ffmpeg 可执行文件路径"""
    if shutil.which("ffmpeg"):
        return os.path.dirname(shutil.which("ffmpeg"))
    try:
        import static_ffmpeg
        paths = static_ffmpeg.run.get_or_fetch_platform_executables_else_raise()
        return os.path.dirname(paths[0])
    except Exception:
        return None


class VideoDownloader:
    """yt-dlp 封装层，提供视频解析、下载、直链获取能力"""

    DOWNLOAD_DIR = os.path.join(os.path.dirname(__file__), "downloads")

    def __init__(self):
        os.makedirs(self.DOWNLOAD_DIR, exist_ok=True)
        self.ffmpeg_path = _find_ffmpeg_path()
        self.has_ffmpeg = self.ffmpeg_path is not None

    @staticmethod
    def _sanitize_filename(name: str) -> str:
        return re.sub(r'[\\/*?:"<>|]', "_", name)

    @staticmethod
    def _format_filesize(size: Optional[int]) -> str:
        if not size:
            return "未知大小"
        if size < 1024 * 1024:
            return f"{size / 1024:.0f}KB"
        if size < 1024 * 1024 * 1024:
            return f"{size / (1024 * 1024):.1f}MB"
        return f"{size / (1024 * 1024 * 1024):.2f}GB"

    @staticmethod
    def _format_duration(seconds: Optional[int]) -> str:
        if not seconds:
            return "00:00"
        hours, remainder = divmod(int(seconds), 3600)
        minutes, secs = divmod(remainder, 60)
        if hours:
            return f"{hours}:{minutes:02d}:{secs:02d}"
        return f"{minutes}:{secs:02d}"

    # ---- Cookie 处理 ----
    # B站会员视频需要登录态。优先使用服务端预置的 cookies.txt 文件，
    # 文件无效时回退到从浏览器读取（需要钥匙串权限）。

    DEFAULT_BILIBILI_COOKIES = os.path.join(
        os.path.dirname(__file__), "bilibili_cookies.txt"
    )

    @classmethod
    def _netscape_has_sessdata(cls, path: str) -> bool:
        """检查 Netscape cookie 文件是否包含非空的 SESSDATA（B站登录态的核心 Cookie）"""
        if not path or not os.path.exists(path):
            return False
        try:
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                for line in f:
                    line = line.rstrip("\n").rstrip("\r")
                    if not line or line.startswith("#") or line.lower().startswith("format"):
                        continue
                    parts = line.split("\t")
                    if len(parts) >= 7 and parts[5] == "SESSDATA" and parts[6].strip():
                        return True
            return False
        except Exception:
            return False

    @staticmethod
    def _is_bilibili(url: str) -> bool:
        return "bilibili.com" in (url or "").lower() or "b23.tv" in (url or "").lower()

    def _write_netscape_from_header(self, cookie_header: str):
        """把 'name=value; name=value' 形式的字符串写成临时 Netscape cookie 文件，返回路径"""
        pairs = {}
        for part in cookie_header.split(";"):
            part = part.strip()
            if not part or "=" not in part:
                continue
            name, value = part.split("=", 1)
            name = name.strip()
            if name:
                pairs[name] = value.strip()
        if "SESSDATA" not in pairs or not pairs["SESSDATA"]:
            return None
        fd, tmp = tempfile.mkstemp(suffix=".txt", prefix="bilibili_cookies_")
        with os.fdopen(fd, "w") as f:
            f.write("# Netscape HTTP Cookie File\n# Generated by VideoDownloader\n")
            expiry = 1900000000
            for name, value in pairs.items():
                secure = "TRUE" if name in ("SESSDATA", "bili_jct", "DedeUserID") else "FALSE"
                f.write(f".bilibili.com\tTRUE\t/\t{secure}\t{expiry}\t{name}\t{value}\n")
        return tmp

    def _build_ydl_opts(self, base_opts: dict, url: str, cookies: str = None) -> dict:
        """构建 yt-dlp 选项，自动处理 Cookie（B站自动使用登录态）"""
        opts = {**base_opts}
        is_bili = self._is_bilibili(url)

        # 1) 显式传入的 cookie 文件路径（最高优先级）
        if cookies and self._netscape_has_sessdata(cookies):
            opts["cookiefile"] = cookies
            return opts

        # 2) B站 + 没有显式 cookies：尝试使用服务端默认文件
        if is_bili and self._netscape_has_sessdata(self.DEFAULT_BILIBILI_COOKIES):
            opts["cookiefile"] = self.DEFAULT_BILIBILI_COOKIES
            return opts

        # 3) B站 + 没有有效文件：尝试从环境变量字符串生成临时文件
        if is_bili:
            env_header = os.getenv("BILIBILI_COOKIES")
            if env_header and "SESSDATA=" in env_header:
                tmp = self._write_netscape_from_header(env_header)
                if tmp:
                    opts["cookiefile"] = tmp
                    return opts

            # 4) 最后回退：直接从浏览器读取（需要钥匙串权限，沙箱里通常失败）
            import sys
            import warnings
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
            opts["cookiesfrombrowser"] = ("chrome",)
            sys.stderr.write(
                "⚠️ B站 Cookie 文件无效或不存在，尝试从 Chrome 浏览器读取登录态...\n"
                "⚠️ 若浏览器读取失败，请运行: python setup_bilibili_cookies.py\n"
            )
            return opts

        # 非 B站：若显式传了 cookies 则使用，否则不加任何 Cookie
        if cookies:
            opts["cookiefile"] = cookies
        return opts

    def parse_video(self, url: str, cookies: str = None) -> dict:
        """解析视频信息，不下载文件"""
        base_opts = {
            "quiet": True,
            "no_warnings": True,
            "extract_flat": False,
            "noplaylist": True,
        }
        ydl_opts = self._build_ydl_opts(base_opts, url, cookies)

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)

        if not info:
            raise ValueError("无法解析该链接")

        formats = self._extract_formats(info)
        platform = info.get("extractor", info.get("extractor_key", "Unknown"))

        return {
            "id": info.get("id", ""),
            "title": info.get("title", "未知标题"),
            "thumbnail": info.get("thumbnail", ""),
            "duration": info.get("duration"),
            "duration_string": self._format_duration(info.get("duration")),
            "uploader": info.get("uploader", info.get("channel", "未知")),
            "platform": platform,
            "view_count": info.get("view_count"),
            "upload_date": info.get("upload_date", ""),
            "description": (info.get("description") or "")[:200],
            "formats": formats,
            "subtitles": list(info.get("subtitles", {}).keys()),
            "automatic_captions": list(info.get("automatic_captions", {}).keys())[:5],
        }

    def _extract_formats(self, info: dict) -> list:
        """从 yt-dlp info 中提取并整理可用格式"""
        raw_formats = info.get("formats", [])
        if not raw_formats:
            return []

        seen = set()
        results = []

        # 识别是否是B站
        is_bilibili = info.get("extractor_key") == "Bilibili" or "bilibili" in info.get("extractor", "").lower()

        # 获取完整视频时长（秒）
        duration = info.get("duration") or 0

        for f in raw_formats:
            vcodec = f.get("vcodec") or ""
            acodec = f.get("acodec") or ""
            height = f.get("height")
            ext = f.get("ext", "mp4")
            format_id = str(f.get("format_id", ""))
            video_ext = f.get("video_ext", "")
            audio_ext = f.get("audio_ext", "")

            # 判断是否有视频：
            # 1. vcodec 不是 "none" 且不为空
            # 2. 或者 video_ext 不是 "none" 且不为空
            # 3. 或者有 height（B站等平台 vcodec 可能是 unknown/None，但有 height 就有视频）
            has_video = (
                (vcodec != "none" and vcodec != "") or
                (video_ext != "none" and video_ext != "") or
                bool(height)
            )

            # 判断是否有音频：
            # 1. acodec 不是 "none" 且不为空
            # 2. 或者 audio_ext 不是 "none" 且不为空
            has_audio = (
                (acodec != "none" and acodec != "") or
                (audio_ext not in ("none", "", "no_audio"))
            )

            if not has_video:
                continue

            resolution = f"{f.get('width', '?')}x{height}" if height else "未知"
            filesize = f.get("filesize") or f.get("filesize_approx")
            size_label = self._format_filesize(filesize)

            # B站特殊处理：判断是否为完整视频
            if is_bilibili:
                # B站的格式 ID 16/32/64 实际上是包含音视频的完整格式
                # yt-dlp 可能报告 audio_ext=none，但实际有音频
                if format_id in ("16", "32", "64", "80", "112", "116"):
                    has_audio = True
                    label = f"{height}p {ext.upper()} ({size_label}) - ⭐ 完整视频"
                elif has_audio:
                    label = f"{height}p {ext.upper()} ({size_label})"
                else:
                    label = f"{height}p {ext.upper()} (仅视频, {size_label})"
            else:
                if has_audio:
                    label = f"{height}p {ext.upper()} ({size_label})"
                else:
                    label = f"{height}p {ext.upper()} (仅视频, {size_label})"

            key = (height, ext, "av" if has_audio else "v")

            if key in seen:
                continue
            seen.add(key)

            results.append({
                "format_id": format_id,
                "ext": ext,
                "resolution": resolution,
                "height": height or 0,
                "filesize": filesize,
                "filesize_approx": filesize,
                "vcodec": vcodec or None,
                "acodec": acodec if has_audio else None,
                "has_audio": has_audio,
                "label": label,
                "is_segment": False,
                "is_likely_full": True,
            })

        results.sort(key=lambda x: x["height"], reverse=True)

        # 如果是B站，添加合并选项（当有独立音视频流时）
        if is_bilibili and self.has_ffmpeg:
            video_only = [f for f in results if not f["has_audio"]]
            audio_only_formats = []
            # 检查原始格式中是否有纯音频格式
            for f in raw_formats:
                ae = f.get("audio_ext", "")
                ve = f.get("video_ext", "")
                if ae not in ("none", "") and ve in ("none", ""):
                    audio_only_formats.append(f)

            if video_only and audio_only_formats:
                best_v = video_only[0]
                merged = {
                    "format_id": "bestvideo+bestaudio",
                    "ext": "mp4",
                    "resolution": best_v["resolution"],
                    "height": best_v["height"],
                    "filesize": (best_v["filesize"] or 0) * 2,
                    "filesize_approx": (best_v["filesize_approx"] or 0) * 2,
                    "vcodec": best_v["vcodec"],
                    "acodec": "merged",
                    "has_audio": True,
                    "label": f"{best_v['height']}p 合并 (视频+音频) - ⭐ 推荐",
                    "is_segment": False,
                    "is_merged": True,
                    "is_likely_full": True,
                }
                results.insert(0, merged)

        # 添加默认的最佳格式
        if results and not any(r.get("is_default") for r in results):
            best_format = results[0]
            default = {
                **best_format,
                "format_id": "best",
                "label": "最佳自动选择 (推荐)",
                "is_default": True,
            }
            results.insert(0, default)

        return results[:15]

    def download_video(self, url: str, format_id: str, cookies: str = None) -> dict:
        """下载视频到服务器临时目录，返回文件路径和元数据"""
        is_bilibili = "bilibili" in url.lower()

        # B站特殊处理格式选择
        if is_bilibili:
            if format_id == "best":
                # 对于B站，best 等价于 bestvideo+bestaudio/best
                # 先尝试合并音视频，失败则用最佳单流
                if self.has_ffmpeg:
                    format_id = "bestvideo+bestaudio/best"
                else:
                    format_id = "best"
            elif format_id == "bestvideo+bestaudio":
                if self.has_ffmpeg:
                    format_id = "bestvideo+bestaudio/best"
                else:
                    format_id = "best"

        # 如果没有ffmpeg且需要合并，回退
        if not self.has_ffmpeg and "+" in format_id:
            format_id = "best"

        ydl_opts = self._build_ydl_opts({
            "format": format_id,
            "outtmpl": os.path.join(self.DOWNLOAD_DIR, "%(title)s.%(ext)s"),
            "quiet": True,
            "no_warnings": True,
            "noplaylist": True,
        }, url, cookies)

        if self.has_ffmpeg:
            ydl_opts["ffmpeg_location"] = self.ffmpeg_path
            ydl_opts["merge_output_format"] = "mp4"

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)

        if not info:
            raise ValueError("下载失败")

        title = self._sanitize_filename(info.get("title", "video"))
        ext = info.get("ext", "mp4")
        filename = f"{title}.{ext}"
        filepath = os.path.join(self.DOWNLOAD_DIR, filename)

        if not os.path.exists(filepath):
            prepared = ydl.prepare_filename(info)
            if os.path.exists(prepared):
                filepath = prepared
                filename = os.path.basename(prepared)
            else:
                for f in os.listdir(self.DOWNLOAD_DIR):
                    if title in f:
                        filepath = os.path.join(self.DOWNLOAD_DIR, f)
                        filename = f
                        break

        return {
            "filepath": filepath,
            "filename": filename,
            "title": info.get("title", "video"),
            "ext": ext,
        }

    def get_direct_url(self, url: str, format_id: str, cookies: str = None) -> dict:
        """获取视频直链"""
        base_opts = {
            "format": format_id,
            "quiet": True,
            "no_warnings": True,
            "noplaylist": True,
        }
        ydl_opts = self._build_ydl_opts(base_opts, url, cookies)

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)

        if not info:
            raise ValueError("无法获取直链")

        direct_url = info.get("url")
        if not direct_url:
            requested = info.get("requested_formats")
            if requested and len(requested) > 0:
                direct_url = requested[0].get("url")

        if not direct_url:
            raise ValueError("该视频不支持直链下载，请使用服务端下载模式")

        return {
            "direct_url": direct_url,
            "ext": info.get("ext", "mp4"),
            "filesize": info.get("filesize") or info.get("filesize_approx"),
            "title": info.get("title", "video"),
        }
