#!/usr/bin/env python3
"""
B站 Cookie 配置工具

由于 Chrome 在 macOS 上使用钥匙串加密 Cookie，自动提取在沙箱环境中不可靠。
本工具提供多种方式让用户配置 B站 Cookie，以便下载会员视频。

使用方法:
    python setup_bilibili_cookies.py

推荐方式（最快）：
1. 在 Chrome 中安装 "Get cookies.txt LOCALLY" 扩展
2. 访问 bilibili.com，在扩展中导出 .bilibili.com 的 Cookie
3. 将导出的 cookies.txt 文件路径提供给本工具

备选方式（无需安装扩展）：
1. 在 Chrome 中访问 bilibili.com 并登录
2. 按 F12 打开开发者工具
3. Application > Cookies > https://www.bilibili.com
4. 复制以下 Cookie 的值：SESSDATA, bili_jct, DedeUserID, DedeUserID__ckMd5
5. 在本工具中粘贴这些值
"""

import os
import sys
from pathlib import Path


# Cookie 输出路径
DEFAULT_OUTPUT = os.path.join(os.path.dirname(__file__), "bilibili_cookies.txt")


def validate_netscape_cookie_file(path: str) -> bool:
    """验证 Netscape 格式的 Cookie 文件是否包含有效的 SESSDATA"""
    if not path or not os.path.exists(path):
        return False
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line = line.rstrip("\n").rstrip("\r")
                if not line or line.startswith("#") or line.lower().startswith("format"):
                    continue
                parts = line.split("\t")
                if len(parts) >= 7 and parts[5] == "SESSDATA" and parts[6].strip():
                    return True
        return False
    except Exception:
        return False


def create_netscape_from_values(sessdata: str, bili_jct: str, dedeuserid: str,
                                 dedeuserid_ckmd5: str = "", sid: str = "") -> str:
    """从手动输入的 Cookie 值创建 Netscape 格式的 Cookie 文件"""
    if not all([sessdata.strip(), bili_jct.strip(), dedeuserid.strip()]):
        print("❌ SESSDATA, bili_jct, DedeUserID 都不能为空")
        return None

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by setup_bilibili_cookies.py",
    ]

    expiry = 1900000000  # 2030年左右，足够长

    # 必需的 Cookie
    cookies = [
        (".bilibili.com", "SESSDATA", sessdata.strip()),
        (".bilibili.com", "bili_jct", bili_jct.strip()),
        (".bilibili.com", "DedeUserID", dedeuserid.strip()),
    ]

    # 可选的 Cookie
    if dedeuserid_ckmd5.strip():
        cookies.append((".bilibili.com", "DedeUserID__ckMd5", dedeuserid_ckmd5.strip()))
    if sid.strip():
        cookies.append((".bilibili.com", "sid", sid.strip()))

    for domain, name, value in cookies:
        secure = "TRUE" if name in ("SESSDATA", "bili_jct", "DedeUserID") else "FALSE"
        lines.append(f"{domain}\tTRUE\t/\t{secure}\t{expiry}\t{name}\t{value}")

    content = "\n".join(lines)
    return content


def method_import_from_file():
    """方法1：从导出的 cookies.txt 文件导入"""
    print("\n=== 方法 1：从 cookies.txt 文件导入 ===")
    print("请在 Chrome 中安装 'Get cookies.txt LOCALLY' 扩展，")
    print("访问 bilibili.com 后导出 .bilibili.com 域名的 Cookie 文件。")
    print("扩展地址: https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclechndkgdckloadeadgfjbghhaidln")
    print()

    file_path = input("请输入导出的 cookies.txt 文件路径（或留空返回）: ").strip()

    if not file_path:
        return None

    # 展开路径
    file_path = os.path.expanduser(file_path)

    if not os.path.exists(file_path):
        print(f"❌ 文件不存在: {file_path}")
        return None

    if validate_netscape_cookie_file(file_path):
        print(f"✅ Cookie 文件验证成功: {file_path}")
        return file_path
    else:
        print(f"❌ Cookie 文件无效，未找到有效的 SESSDATA")
        print("请确保导出的是 .bilibili.com 域名的 Cookie")
        return None


def method_manual_input():
    """方法2：手动输入 Cookie 值"""
    print("\n=== 方法 2：手动输入 Cookie 值 ===")
    print("请在 Chrome 中按 F12 打开开发者工具，")
    print("Application > Cookies > https://www.bilibili.com")
    print("复制以下 Cookie 的值：")
    print()

    sessdata = input("SESSDATA (必需): ").strip()
    bili_jct = input("bili_jct (必需): ").strip()
    dedeuserid = input("DedeUserID (必需): ").strip()

    if not all([sessdata, bili_jct, dedeuserid]):
        print("\n❌ SESSDATA, bili_jct, DedeUserID 都是必需的")
        return None

    print("\n可选 Cookie（直接回车跳过）：")
    dedeuserid_ckmd5 = input("DedeUserID__ckMd5 (可选): ").strip()
    sid = input("sid (可选): ").strip()

    content = create_netscape_from_values(sessdata, bili_jct, dedeuserid, dedeuserid_ckmd5, sid)

    if not content:
        return None

    # 写入临时文件
    fd, tmp_path = tempfile.mkstemp(suffix=".txt", prefix="bilibili_cookies_")
    with os.fdopen(fd, "w") as f:
        f.write(content)

    print(f"\n✅ Cookie 内容已生成")
    print(f"验证结果: {'✅ 包含 SESSDATA' if validate_netscape_cookie_file(tmp_path) else '❌ 验证失败'}")
    return tmp_path


def copy_to_output(source_path: str) -> bool:
    """将 Cookie 文件复制到目标位置"""
    try:
        import shutil
        shutil.copy2(source_path, DEFAULT_OUTPUT)
        print(f"\n✅ Cookie 文件已保存到: {DEFAULT_OUTPUT}")
        return True
    except Exception as e:
        print(f"❌ 保存文件失败: {e}")
        return False


def show_existing_status():
    """显示现有 Cookie 文件的状态"""
    if os.path.exists(DEFAULT_OUTPUT):
        if validate_netscape_cookie_file(DEFAULT_OUTPUT):
            print(f"✅ 现有 Cookie 文件有效: {DEFAULT_OUTPUT}")
            return True
        else:
            print(f"⚠️ 现有 Cookie 文件存在但无效（SESSDATA 为空）: {DEFAULT_OUTPUT}")
            return False
    else:
        print(f"⚠️ 不存在 Cookie 文件: {DEFAULT_OUTPUT}")
        return False


def test_cookie():
    """测试 Cookie 是否有效（可选）"""
    print("\n=== 测试 Cookie（可选）===", end="", flush=True)
    test_url = input("是否测试 Cookie？输入一个 B站视频 URL（或留空跳过）: ").strip()

    if not test_url:
        return

    try:
        from downloader import VideoDownloader
        downloader = VideoDownloader()
        print(f"\n正在解析视频: {test_url}")

        info = downloader.parse_video(test_url)
        print(f"✅ 解析成功！")
        print(f"   标题: {info['title']}")
        print(f"   时长: {info['duration_string']}")
        print(f"   平台: {info['platform']}")
        print(f"   可用格式: {len(info['formats'])}个")
        print("\n前 3 个格式:")
        for i, fmt in enumerate(info['formats'][:3], 1):
            print(f"   {i}. {fmt['label']}")
        print("\n✅ Cookie 测试通过！")

    except Exception as e:
        print(f"\n❌ Cookie 测试失败: {e}")
        print("可能的原因：")
        print("  1. Cookie 已过期")
        print("  2. 账号没有该视频的观看权限")
        print("  3. 视频链接错误")


def main():
    print("=" * 60)
    print("B站 Cookie 配置工具")
    print("=" * 60)
    print("\n本工具用于配置 B站 Cookie 以支持会员视频下载。")
    print("由于 Chrome 在 macOS 上使用钥匙串加密 Cookie，")
    print("自动提取不可靠，因此需要手动配置。")
    print()

    # 显示现有状态
    existing_valid = show_existing_status()
    print()

    if existing_valid:
        choice = input("现有 Cookie 已有效，是否重新配置？(y/N): ").strip().lower()
        if choice != 'y':
            print("\n使用现有 Cookie，配置完成。")
            print("您现在可以直接从 Web 界面下载 B站会员视频。")
            return

    # 选择配置方法
    print("\n请选择配置方式：")
    print("  1. 从 cookies.txt 文件导入（推荐，需要安装浏览器扩展）")
    print("  2. 手动输入 Cookie 值（无需安装扩展）")

    choice = input("\n请输入选项 (1/2, 默认 1): ").strip()

    if choice == "2":
        source_path = method_manual_input()
    else:
        source_path = method_import_from_file()

    if not source_path:
        print("\n❌ 未配置 Cookie")
        print("请重试，或者参考文档手动创建 Cookie 文件。")
        return

    # 复制到目标位置
    if copy_to_output(source_path):
        print("\n✅ Cookie 配置成功！")
        print()
        print("使用说明：")
        print("  1. 重启后端服务（如果正在运行）：")
        print("     cd backend && python main.py")
        print("  2. 访问 Web 界面: http://localhost:5173")
        print("  3. 输入 B站会员视频 URL，即可下载")

        # 可选测试
        test_cookie()
    else:
        print("\n❌ 配置失败，请检查文件权限")


if __name__ == "__main__":
    # 导入 tempfile
    import tempfile
    main()